name: Kernel Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        bc \
        bison \
        build-essential \
        flex \
        libssl-dev \
        libelf-dev \
        wget \
        cpio \
        python3

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Run build script
      run: ./build.sh

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: out/arch/arm64/boot/*
